### ISSUE TITLE
Cleaner prefixer mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#3]
The `prefixer` mixin does the job well but could be made slightly more elegant:

``` scss
// Utility for prefixing mixins
@mixin prefixer($property, $value, $prefixes: webkit moz) {
  @each $prefix in $prefixes {
    #{"-" + $prefix + "-" + $property}: $value;
  }
  #{$property}: $value;
}
```

Per default, only use `webkit` and `moz` prefixes which are by far more used than others, with the ability to add more if needed by specifying the 3rd argument.

This also gets rid off the `spec` prefix which is rather useless. The unprefixed rule shoud **always** be specified, no matter what.

**Comment by kenwheeler** [comment]
Good call.

**Comment by kenwheeler** [comment]
Done

**Comment by KittyGiraudel** [comment]
Doesn't seem to be done on the current state of repository. Did I miss something?

**Comment by kenwheeler** [comment]
Yikes, its up there now
