### ISSUE TITLE
Simpler transition mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#4]
I have yet to come across a use-case where it makes sense to specify various transitions for the transition property, even if that is technically possible. Since the framework's motto is "keep this shit simple", I'd suggest the following:

``` scss
@mixin transition($transition: .15s) {
  @include prefixer(transition, $transition, webkit moz); // See #3
}
```

We set the default value in the mixin signature to keep things simple. The duration is the only required parameter. Everything else has a default value.

**Comment by kenwheeler** [comment]
I'm not sure what you are asking? You want the argument to be duration alone? As opposed to 'all 1s linear'?

**Comment by KittyGiraudel** [comment]
Not quite. I'm suggesting three changes here:
1. Ditching the whole "there might be multiple transitions specified" ; it never happens. Thus we don't need an argList for this.
2. Moving the default value to the function signature instead of the mixin core.
3. Making the default value shorter : `.15s` is the same as `all 0.15s ease 0s`.

**Comment by kenwheeler** [comment]
Ah ok. Seems about right. I'll add this to tonights work.

**Comment by kenwheeler** [comment]
Fixed
