### ISSUE TITLE
Using Sass maps

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#6]
I feel like you could make some good use of Sass maps, especially when it comes to breakpoints for responsive design.

What about something like:

``` scss
$breakpoints: (
  "desktop": (
    min: 1024
  ),
  "tablet":
    min: 768,
    max: 1023
  ),
  "mobile": (
    max: 767
  )
);
```

Although we are talking about Sass elegance here more than a real need. I'm not sure I like having strings for breakpoints like `"(min-width: 1024px)"`. I'd rather have a conf map handling this for me.

The API for calling a breakpoint would be slightly different since you'd be passing a keyword rather than a variable name: `@include breakpoint("desktop")`.

Highly personnal though.

**Comment by kenwheeler** [comment]
I thought about it, but I was concerned whether map syntax would make it less accessible for those not familiar with them. What do you think?

**Comment by KittyGiraudel** [comment]
I think hashes are popular enough to be used without worrying.

**Comment by kenwheeler** [comment]
Ok, I'm gonna play with this for a little and see what makes the most sense structure-wise. What do you think about a mixin that merges the defaults with a map of user settings?

**Comment by kenwheeler** [comment]
So libsass (node-sass, gulp-sass), doesn't support the map type yet. I'm not gonna make this hard a dependency until they add support. But I can't wait to, because everything will neaten up nicely.

**Comment by niallobrien** [comment]
Fingers crossed. :)
