### ISSUE TITLE
Inconsistency in inline-list

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#7]
The `inline-list` mixin currently apply `margin-right: 0`  to the last item of list. Since it doesn't add any margin whatsoever, I don't think this rule should be there.

Moreover, if you still want to use a mixin rather than a placeholder, I'd suggest you add a `$method` parameter accepting either `float` or `inline-block` as value, which then defines whether the items are floated or displayed as inline-blocks.

**Comment by kenwheeler** [comment]
Great call

**Comment by kenwheeler** [comment]
Fixed
