### ISSUE TITLE
About unit stripping in convert-to-rem

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#9]
Since you use `strip-unit` either way, why don't you turn `@if ($value == 0rem) { $value: 0; }` into `@if strip-unit($value) == 0 { $value: 0 }` (in [_functions.scss:11](https://github.com/kenwheeler/guff/blob/master/src/_functions.scss#L11))?

That being said, it shouldn't change much.

**Comment by kenwheeler** [comment]
Fixed
